### ISSUE TITLE
Migrate wikidirect.php from old site to current one 

### ISSUE THREAD

**Issue by proycon** [proycon/unilangforum#22]
As suggested in #21

**Comment by lromao** [comment]
Nevermind. I just noticed it's there already! Apparently there's an issue with it not working with some language codes, but I can try to check what the problem is there. Doesn't seem to be migration related.

**Comment by lromao** [comment]
Oh, never mind again (I need to get some sleep :P). It's not there. I was looking at a version from 2013 I still had in my computer.

**Comment by Yserenhart** [comment]
wikidirect was migrated when the forum was updated. It's part of "unilangforum/phpBB3/ext/unilang/languages/controller/main.php". Possibly the reason it doesn't work is because the BBCode isn't calling that function. The relevant part of the BBcode is `<a href="http://forum.unilang.org/wikidirect.php?lang={SIMPLETEXT}" title="({SIMPLETEXT})">`.

**Comment by lromao** [comment]
Wasn't that pointing to http://www.unilang.org/wikidirect.php even yesterday though?

**Comment by Yserenhart** [comment]
It was, I changed it when I fixed the other issue with the flag BBCode. I remembered that we had migrated wikidirect when we updated the software, but I didn't remember exactly how it was done. Figured that changing the URL might be enough, clearly it wasn't.

**Comment by lromao** [comment]
Just had a look at the routing. Turns out it's just wikidirect and not wikidirect.php. I changed the BBCode and it works fine now.

`http://forum.unilang.org/wikidirect?lang=see`
